### ISSUE TITLE
Thriftpy and cython issue 

### ISSUE THREAD

**Issue by gpatera** [eleme/thriftpy#171]
Hi
I'm trying to install ibis on Ubuntu with anaconda 3.5 but when I do "import ibis"
i get this error

```python
   from ibis.impala.client import (ImpalaConnection,  # noqa
  File "/home/pino/anaconda3/lib/python3.5/site-packages/ibis/impala/client.py", line 34, in <module>
    from ibis.impala.compat import impyla, ImpylaError, HS2Error
  File "/home/pino/anaconda3/lib/python3.5/site-packages/ibis/impala/compat.py", line 17, in <module>
    import impala.dbapi as impyla  # noqa
  File "/home/pino/anaconda3/lib/python3.5/site-packages/impala/dbapi.py", line 28, in <module>
    import impala.hiveserver2 as hs2
  File "/home/pino/anaconda3/lib/python3.5/site-packages/impala/hiveserver2.py", line 32, in <module>
    from impala._thrift_api import (
  File "/home/pino/anaconda3/lib/python3.5/site-packages/impala/_thrift_api.py", line 62, in <module>
    from thriftpy.protocol.binary import TBinaryProtocol  # noqa
  File "/home/pino/anaconda3/lib/python3.5/site-packages/thriftpy/protocol/__init__.py", line 13, in <module>
    from .cybin import TCyBinaryProtocol, TCyBinaryProtocolFactory
ImportError: No module named 'thriftpy.protocol.cybin'
```

Any idea?

Thanks

**Comment by gpatera** [comment]
I downgraded to python 3.4 and it works. The issue seems related to 3.5

**Comment by lxyu** [comment]
What's your `wheel` version? There's a bug in `wheel` that will fail the cython build, which was fixed in `>=0.25`. Can you check it please?

**Comment by lxyu** [comment]
Close as it should be caused by another package, `wheel`. Feel free to reopen if it's not.

**Comment by bhgames** [comment]
I had wheel version 0.30.0.a0 and this still happened for both 3.4.3 and 3.5.
